repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-docstring-first
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.0.272
      hooks:
          - id: ruff
            args:
                - "--fix"
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.10.1
      hooks:
          - id: pyupgrade
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.5.0
      hooks:
          - id: mypy
            additional_dependencies: [types-requests==2.25, types-setuptools]
