[tool.poetry]
name = "ksp-price-notifier"
version = "0.1.0"
description = ""
authors = ["Bar Hochman <bhochman@paloaltonetworks.com>"]

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.4.0"
click = "8.0.0"

[tool.poetry.dev-dependencies]
pylint = "^2.13.3"
mypy = "^0.942"
flake8 = "^4.0.1"
rstcheck = "^3.3.1"
requests-mock = "^1.9.3"
doc8 = "^0.10.1"
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
