name: Deploy

on:
  push:
    tags:
      - v*.**

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - name: Run tests
        uses: jochman/KSP-Price-Notifier/.github/workflows/push.yml@main
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.10
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
