name: Deploy

on:
  push:
    tags:
      - v*.**
    branches:
      - workflow-call
jobs:
  tests:
    uses: jochman/KSP-Price-Notifier/.github/workflows/push.yml@workflow-call
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.10
        with:
          pypi_token: ${{ secrets.sPYPI_TOKEN }}
