name: Deploy

on:
  push:
    tags:
      - v*.**

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.10
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            To install go to [PyPi](https://pypi.org/project/ksp-price-notifier/)

            See changelog at [here](https://github.com/jochman/KSP-Price-Notifier/blob/main/CHANGELOG.md)
          draft: false
          prerelease: false
